package templates

const ClientTemplate = `// Code generated by protoc-gen-connection; DO NOT EDIT.
package {{ .PackageName }}

import (
	gomock "github.com/golang/mock/gomock"
{{- range .Packages }}
	{{ .Alias }} "{{ .Name }}"
{{- end }}
)

type client struct {
{{- range .Services }}
	{{ .Name }} {{ .Package }}.{{ .Name }}Client
{{- end }}
}

func (s *Service) getClient () {
{{- range .Services }}
	s.Client.{{ .Name }} = {{ .Package }}.New{{ .Name }}Client(s.conn.{{ .Service }})
{{- end }}
}

func (s *Service) getMockClient (ctrl *gomock.Controller) {
{{- range .Services }}
	s.Client.{{ .Name }} = {{ .Package }}.NewMock{{ .Name }}Client(ctrl)
{{- end }}
}

type MockClient struct {
{{- range .Services }}
	{{ .Name }} *{{ .Package }}.Mock{{ .Name }}Client
{{- end }}
}

func (c *MockClient) MockAssign(resource *client) {
{{- range .Services }}
	c.{{ .Name }} = resource.{{ .Name }}.(*{{ .Package }}.Mock{{ .Name }}Client)
{{- end }}
}
`
