package templates

const ClientTemplate = `// Code generated by protoc-gen-connection; DO NOT EDIT.
package {{ .PackageName }}

import (
{{- range .Packages }}
	{{ .Alias }} "{{ .Name }}"
{{- end }}
)

type client struct {
{{- range .Services }}
	{{ .Name }} {{ .Package }}.{{ .Name }}Client
{{- end }}
}

func (s *Service) getClient () {
{{- range .Services }}
	s.Client.{{ .Name }} = {{ .Package }}.New{{ .Name }}Client(s.conn.{{ .Service }})
{{- end }}
}
`
